INSERT INTO PERMISSIONS VALUES(1, 'VIEW_TASKS');
INSERT INTO PERMISSIONS VALUES(2, 'ADD_TASKS');
INSERT INTO PERMISSIONS VALUES(3, 'EDIT_TASKS');
INSERT INTO PERMISSIONS VALUES(4, 'DELETE_TASKS');

SELECT * FROM PERMISSIONS;

INSERT INTO ROLES VALUES(1, 'EMPLOYEE');
INSERT INTO ROLES VALUES(2, 'MANAGER');
INSERT INTO ROLES VALUES(3, 'SUPER_ADMIN');

SELECT * FROM ROLES;

INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(1, 1);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(1, 3);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(2, 1);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(2, 2);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(2, 3);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(2, 4);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(3, 1);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(3, 2);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(3, 3);
INSERT INTO ROLES_PERMISSIONS (role_id, permission_id) VALUES(3, 4);

SELECT * FROM ROLES_PERMISSIONS;

