INSERT INTO PERMISSIONS VALUES(1, 'VIEW_TASKS');
INSERT INTO PERMISSIONS VALUES(2, 'ADD_TASKS');
INSERT INTO PERMISSIONS VALUES(3, 'EDIT_TASKS');
INSERT INTO PERMISSIONS VALUES(4, 'DELETE_TASKS');
INSERT INTO PERMISSIONS VALUES(5, 'VIEW_PROJECTS');
INSERT INTO PERMISSIONS VALUES(6, 'ADD_PROJECTS');
INSERT INTO PERMISSIONS VALUES(7, 'EDIT_PROJECTS');
INSERT INTO PERMISSIONS VALUES(8, 'DELETE_PROJECTS');
INSERT INTO PERMISSIONS VALUES(9, 'VIEW_ROLES');
INSERT INTO PERMISSIONS VALUES(10, 'ADD_ROLES');
INSERT INTO PERMISSIONS VALUES(11, 'EDIT_ROLES');
INSERT INTO PERMISSIONS VALUES(12, 'DELETE_ROLES');

INSERT INTO ROLES VALUES('3fa85f64-5717-4562-b3fc-2c963f66afa6', 'SUPER_ADMIN');
INSERT INTO ROLES VALUES('8719715c-46cb-474c-93b0-31e6f1503a18', 'EMPLOYEE');
