
INSERT INTO PERMISSIONS VALUES(1, 'VIEW_TASKS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(2, 'ADD_TASKS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(3, 'EDIT_TASKS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(4, 'DELETE_TASKS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(5, 'VIEW_PROJECTS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(6, 'ADD_PROJECTS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(7, 'EDIT_PROJECTS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(8, 'DELETE_PROJECTS') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(9, 'VIEW_ROLES') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(10, 'ADD_ROLES') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(11, 'EDIT_ROLES') ON CONFLICT (id) DO NOTHING;
INSERT INTO PERMISSIONS VALUES(12, 'DELETE_ROLES') ON CONFLICT (id) DO NOTHING;

INSERT INTO ROLES VALUES('3fa85f64-5717-4562-b3fc-2c963f66afa6', 'SUPER_ADMIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO ROLES VALUES('8719715c-46cb-474c-93b0-31e6f1503a18', 'EMPLOYEE') ON CONFLICT (id) DO NOTHING;
