name: build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Backend Image
        run: docker build -t task-management-be .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Image
        run: |
          docker tag task-management-be ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:latest
          docker tag task-management-be ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:${{ github.sha }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:${{ github.sha }}
