name: CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Backend Image
        run: docker build -t task-management-be .

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Tag Image
        run: |
          docker build -t task-management-be .
          docker tag task-management-be ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:latest
          docker tag task-management-be ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:${{ github.sha }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-management-be:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} "
            cd /home/ec2-user/backend &&
            docker compose pull &&
            docker compose up -d --remove-orphans
          "
